### ISSUE TITLE
1.3.0 cloudpickle.load hits AttributeError: module 'types' has no attribute 'ClassType'

### ISSUE THREAD

**Issue by mzhang-code** [cloudpipe/cloudpickle#349]
After upgrading to 1.3.0 from 1.2.2, our load() code starts having this issue.

```
 File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 415, in _builtin_type
     return getattr(types, name)
 AttributeError: module 'types' has no attribute 'ClassType'
```

Also found this post described the same issue we got. https://github.com/mlflow/mlflow/issues/2429

I suspect it is caused by https://github.com/cloudpipe/cloudpickle/pull/337 "Fix a side effect that would redefine types.ClassTypes as type when importing cloudpickle", which removed `types.ClassType = type`

**Comment by ogrisel** [comment]
Coming back to this issue. As per cloudpickle's README and and as I replied in https://github.com/mlflow/mlflow/issues/2429#issuecomment-619837699 , cloudpickle does not support loading objects from prior versions as it's only meant to transient object flowing between the nodes of a cluster.

That being said we could temporarily do an effort for backward compat this time with something like:

```python
if not hasattr(types, "ClassType"):
    types.ClassType = type
```

but this is weird and I would rather not have this on the long term.

**Comment by pierreglaser** [comment]
> That being said we could temporarily do an effort for backward compat this time with something like:

I'm afraid the proposed workaround will end up recreating the problem reported in #337.

**Comment by pierreglaser** [comment]
What might work though is special-casing `type` in 
https://github.com/cloudpipe/cloudpickle/blob/a69b92d4ea67befceb7b40a3754400b8fd8e2098/cloudpickle/cloudpickle.py#L390-L391

**Comment by ogrisel** [comment]
Yes, this is what I was coming to by reading the reports. Let's add a small compat fix there.

**Comment by ogrisel** [comment]
Compat fix implemented in #359.
